---
title: "R Notebook"
output: html_notebook
---

```{r}
# install.packages("xlsx")
# install.packages("rJava")
```
```{r}
library(readr)
library(dplyr)
data <- read_csv("Users/mdarfler/Google\ Drive/Grad\ School/DAIL/A3\ Behavior\ Data\ Analysis/A3_Analysis_Code_Repo/A3 Accuracy Analysis - A3 Accuracy.csv")
```
```{r}
data_clean <- select(data,'X1','Condition','Start Time','Timepoints for Incorrect Answers','Duration')
for(p in 6:23){
pnumber = p
participant = subset(data_clean,data_clean$X1 == pnumber);

eegTags = data.frame("tag" = "NA", "timeStamp" = "00:00","duration" = 0, stringsAsFactors = FALSE)

for(j in 1:dim(participant)[2]){
  workingCondition <- participant[j,]
  st <- strsplit(unlist(strsplit(workingCondition$`Start Time`,"\n")),": ")
  incorrect <- strsplit(unlist(strsplit(workingCondition$`Timepoints for Incorrect Answers`,"\n")),": ")
  duration <- strsplit(unlist(strsplit(workingCondition$`Duration`,"\n")),": ")

  condition <- gsub(" ","_",participant$Condition[j])
  tagEnd = paste(condition,"Start",sep = "_")
  
  
  for(i in 1:length(st)){
    tag = paste(st[[i]][1],tagEnd,sep="_")
    st_temp = paste("00:",st[[i]][2],sep="")
    d = duration[[i]][2]
    l = list(tag,st_temp,d)
    eegTags <-  rbind(eegTags,l)
  }
  
  flatIncorrect <- 
    strsplit(unlist(strsplit(participant$`Timepoints for Incorrect Answers`[j],"\n")),": ")
  
    for(i in 1:length(flatIncorrect)){
      flatIncorrect[[i]][2] <- strsplit(flatIncorrect[[i]][2],", ")
  }

  flatIncorrect <- unlist(flatIncorrect,recursive = F)
  
  tagEnd = paste(condition,"Incorrect",sep = "_")
  
  for(i in seq(1,length(flatIncorrect),2)){
    tag = paste(flatIncorrect[[i]],tagEnd,sep="_")
    for(k in 1:length(flatIncorrect[[i+1]])){
      incorrectTime = paste("00:",flatIncorrect[[i+1]][k],sep="")
      l <- list(tag,incorrectTime,1)
      eegTags <- rbind(eegTags,l)
    }
  }
}

eegTags <- eegTags[order(eegTags$timeStamp),]

filename = paste("/participant",pnumber,".csv",sep="")
write.csv(eegTags, paste("/Users/mdarfler/Google\ Drive/Grad\ School/DAIL/A3\ Behavior\ Data\ Analysis/A3_Analysis_Code_Repo/EEG\ Tag\ Sheets",pnumber,".csv",sep=""), row.names = FALSE)
}
```
```{r}
for(p in 25:36){
pnumber = p
participant = subset(data_clean,data_clean$X1 == pnumber);

eegTags = data.frame("tag" = "NA", "timeStamp" = "00:00","duration" = 0, stringsAsFactors = FALSE)

for(j in 1:dim(participant)[2]){
  workingCondition <- participant[j,]
  st <- strsplit(unlist(strsplit(workingCondition$`Start Time`,"\n")),": ")
  incorrect <- strsplit(unlist(strsplit(workingCondition$`Timepoints for Incorrect Answers`,"\n")),": ")
  duration <- strsplit(unlist(strsplit(workingCondition$`Duration`,"\n")),": ")

  condition <- gsub(" ","_",participant$Condition[j])
  tagEnd = paste(condition,"start",sep = "_")
  
  
  for(i in 1:length(st)){
    tag = paste(st[[i]][1],tagEnd,sep="_")
    st_temp = st[[i]][2]
    d = duration[[i]][2]
    l = list(tag,st_temp,d)
    eegTags <-  rbind(eegTags,l)
  }
  
  flatIncorrect <- 
    strsplit(unlist(strsplit(participant$`Timepoints for Incorrect Answers`[j],"\n")),": ")
  
    for(i in 1:length(flatIncorrect)){
      flatIncorrect[[i]][2] <- strsplit(flatIncorrect[[i]][2],", ")
  }

  flatIncorrect <- unlist(flatIncorrect,recursive = F)
  
  tagEnd = paste(condition,"Incorrect",sep = "_")
  
  for(i in seq(1,length(flatIncorrect),2)){
    tag = paste(flatIncorrect[[i]],tagEnd,sep="_")
    for(k in 1:length(flatIncorrect[[i+1]])){
      incorrectTime = flatIncorrect[[i+1]][k]
      l <- list(tag,incorrectTime,1)
      eegTags <- rbind(eegTags,l)
    }
  }
}

eegTags <- eegTags[order(eegTags$timeStamp),]

filename = paste("/participant",pnumber,".csv",sep="")
write.csv(eegTags, paste("/Users/mdarfler/Google\ Drive/Grad\ School/DAIL/A3\ Behavior\ Data\ Analysis/A3_Analysis_Code_Repo/EEG\ Tag\ Sheets",pnumber,".csv",sep=""), row.names = FALSE)
}
```

